# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

version: "3.8"

services:
  retriever:
    image: ai-agents/retriever:latest
    container_name: retriever-redis-server
    ports:
      - "5007:7000"
    ipc: host
    depends_on:
      - redis-vector-db
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      REDIS_URL: ${REDIS_URL}
      INDEX_NAME: ${INDEX_NAME}
      TEI_EMBEDDING_ENDPOINT: http://tei-embedding-service:80
      HUGGINGFACEHUB_API_TOKEN: ${HUGGINGFACEHUB_API_TOKEN}
    restart: unless-stopped
  redis-vector-db:
    image: redis/redis-stack:7.2.0-v9
    container_name: redis-vector-db
    ports:
      - "1379:6379"
      - "1001:8001"
  
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      MONGO_INITDB_ROOT_USERNAME: agents
      MONGO_INITDB_ROOT_PASSWORD: agents
    restart: unless-stopped
  
  groq-service:
    image: ai-agents/groq:latest
    container_name: groq-service
    ports:
      - "5099:8000"
    volumes:
      - "${HF_CACHE}:/root/.cache"
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      GROQ_API_KEY: ${GROQ_API_KEY}
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
  
  tei-reranking-service:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.7
    container_name: tei-reranking-server
    ports:
      - "8808:80"
    volumes:
      - ${HF_CACHE}:/data
    shm_size: 1g
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      RERANK_MODEL_ID: ${RERANK_MODEL_ID}
      HUGGINGFACEHUB_API_TOKEN: ${HUGGINGFACEHUB_API_TOKEN}
    command: --model-id ${RERANK_MODEL_ID} --auto-truncate
  
  tei-embedding-service:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.7
    container_name: tei-embedding-server
    ports:
      - "6006:80"
    volumes:
      - ${HF_CACHE}:/data
    shm_size: 1g
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      EMBEDDING_MODEL_ID: ${EMBEDDING_MODEL_ID}
      HUGGINGFACEHUB_API_TOKEN: ${HUGGINGFACEHUB_API_TOKEN}
    command: --model-id ${EMBEDDING_MODEL_ID} --auto-truncate


  dataprep-redis:
    image: ai-agents/dataprep:latest
    container_name: research-dataprep-redis-server
    depends_on:
      - redis-vector-db
      - tei-embedding-service
    volumes:
      - ${HF_CACHE}:/home/user/.cache
    ports:
      - "1006:6007"
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      REDIS_URL: ${REDIS_URL}
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      LOGFLAG: ${LOGFLAG}
      TEI_ENDPOINT: http://tei-embedding-service:80
      HUGGINGFACEHUB_API_TOKEN: ${HUGGINGFACEHUB_API_TOKEN}
      SERVER_HOST_IP: ${LLM_SERVER_HOST_IP}
      SERVER_PORT: ${LLM_SERVER_PORT}
    restart: unless-stopped

  
  backend:
    image: ai-agents/rag/backend:latest
    depends_on:
      - redis-vector-db
      - tei-embedding-service
      - retriever
      - tei-reranking-service
      - groq-service
    ports:
      - "5008:9000"
    environment:
      - no_proxy=${no_proxy}
      - https_proxy=${https_proxy}
      - http_proxy=${http_proxy}
      - MEGA_SERVICE_HOST_IP=${SERVER_HOST_URL}
      - EMBEDDING_SERVER_HOST_IP=${EMBEDDING_SERVER_HOST_IP}
      - EMBEDDING_SERVER_PORT=${EMBEDDING_SERVER_PORT:-80}
      - RETRIEVER_SERVICE_HOST_IP=${RETRIEVER_SERVICE_HOST_IP}
      - RETRIEVER_SERVICE_PORT=${RETRIEVER_SERVICE_PORT}
      - RERANK_SERVER_HOST_IP=${RERANK_SERVER_HOST_IP}
      - RERANK_SERVER_PORT=${RERANK_SERVER_PORT:-80}
      - LLM_SERVER_HOST_IP=${LLM_SERVER_HOST_IP}
      - LLM_SERVER_PORT=${LLM_SERVER_PORT:-80}
      - LLM_MODEL=${LLM_MODEL_ID}
      - LOGFLAG=${LOGFLAG}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_USERNAME=agents
      - MONGO_PASSWORD=agents
      - MONGO_URI=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017
      - WHISPER_SERVICE_HOST_IP=${WHISPER_SERVICE_HOST_IP}
      - RETRIEVER_SERVICE_PORT=7000
    ipc: host
    restart: always
  
  ui:
    image: ai-agents/rag/ui:latest
    depends_on:
      - backend
    ports:
      - "5009:3000"
    environment:
      - no_proxy=${no_proxy}
      - https_proxy=${https_proxy}
      - http_proxy=${http_proxy}
    restart: always

networks:
  default:
    driver: bridge