apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: research-assistant-tei-reranking-deployment
  name: research-assistant-tei-reranking-deployment
  namespace: research-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: research-assistant-tei-reranking-deployment
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: research-assistant-tei-reranking-deployment
    spec:
      nodeSelector:
        kubernetes.io/hostname: g2-r1-2
      containers:
        - args:
            - --model-id
            - BAAI/bge-reranker-base
            - --auto-truncate
          env:
            - name: HF_HUB_DISABLE_PROGRESS_BARS
              value: "1"
            - name: HF_HUB_ENABLE_HF_TRANSFER
              value: "0"
            - name: http_proxy
              value: http://proxy-dmz.intel.com:912
            - name: https_proxy
              value: http://proxy-dmz.intel.com:912
            - name: HTTPS_PROXY
              value: http://proxy-dmz.intel.com:912
            - name: HTTP_PROXY
              value: http://proxy-dmz.intel.com:912
            - name: HUGGINGFACEHUB_API_TOKEN
              value: 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
            - name: no_proxy
              value: 127.0.0.1,localhost,.intel.com
          image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.5
          name: research-assistant-tei-reranking-container
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: ~/.cache/huggingface/hub
              name: research-assistant-tei-reranking-claim0
      restartPolicy: Always
      volumes:
        - name: research-assistant-tei-reranking-claim0
          hostPath:
            path: /mnt/hf_cache
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: research-assistant-tei-reranking-deployment
  name: research-assistant-tei-reranking-deployment
  namespace: research-assistant
spec:
  type: NodePort
  ports:
    - name: "8820"
      port: 8820
      protocol: TCP
      targetPort: 80
      nodePort: 30107
  selector:
    io.kompose.service: research-assistant-tei-reranking-deployment