apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: student-companion-redis-deployment
  name: student-companion-redis-deployment
  namespace: student-companion
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: student-companion-redis-deployment
  template:
    metadata:
      annotations:
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: student-companion-redis-deployment
    spec:
      nodeSelector:
        kubernetes.io/hostname: g2-r1-2
      containers:
        - image: redis/redis-stack:7.2.0-v9
          name: student-companion-redis-container
          ports:
            - containerPort: 6379
              protocol: TCP
            - containerPort: 8001
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: student-companion-redis-deployment
  name: student-companion-redis-deployment
  namespace: student-companion
spec:
  type: NodePort
  ports:
    - name: "6321"
      port: 6321
      protocol: TCP
      targetPort: 6379
      nodePort: 31110
    - name: "8003"
      port: 8003
      protocol: TCP
      targetPort: 8001
  selector:
    io.kompose.service: student-companion-redis-deployment