apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: research-assistant-dataprep-deployment
  name: research-assistant-dataprep-deployment
  namespace: research-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: research-assistant-dataprep-deployment
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: research-assistant-dataprep-deployment
    spec:
      nodeSelector:
        kubernetes.io/hostname: g2-r1-2
      containers:
        - env:
            - name: http_proxy
              value: http://proxy-dmz.intel.com:912
            - name: https_proxy
              value: http://proxy-dmz.intel.com:912
            - name: HTTPS_PROXY
              value: http://proxy-dmz.intel.com:912
            - name: HTTP_PROXY
              value: http://proxy-dmz.intel.com:912
            - name: HUGGINGFACEHUB_API_TOKEN
              value: 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
            - name: LLM_SERVER_HOST_IP
              value: research-assistant-groq-deployment
            - name: LLM_SERVER_PORT
              value: "5020"
            - name: LOGFLAG
              value: "true"
            - name: REDIS_URL
              value: redis://research-assistant-redis-deployment:6321
            - name: TEI_EMBEDDING_ENDPOINT
              value: http://research-assistant-tei-embedding-deployment:6020
            - name: no_proxy
              value: 127.0.0.1,localhost,.intel.com,research-assistant-redis-deployment,research-assistant-groq-deployment
          image: tanmayudupa124/easy-circulars-dataprep:latest
          name: research-assistant-dataprep-container
          ports:
            - containerPort: 6009
              protocol: TCP
          volumeMounts:
            - mountPath: ~/.cache/huggingface/hub
              name: research-assistant-tei-reranking-claim0
      restartPolicy: Always
      volumes:
        - name: research-assistant-tei-reranking-claim0
          hostPath:
            path: /mnt/hf_cache
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: research-assistant-dataprep-deployment
  name: research-assistant-dataprep-deployment
  namespace: research-assistant
spec:
  type: NodePort
  ports:
    - name: "5099"
      port: 5099
      protocol: TCP
      targetPort: 6007
      nodePort: 30101
  selector:
    io.kompose.service: research-assistant-dataprep-deployment